apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: notes-app
spec:
  type: ClusterIP   # Must stay private (Ingress only)
  selector:
    app: frontend
  ports:
    - name: http
      port: 80          # Ingress talks to this
      targetPort: 5000  # Container still listens on 5000
